version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "loggy"
s3_bucket = "CHANGE_ME"
s3_prefix = "loggy"
region = "CHANGE_ME"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
